//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Unity.Analyzers.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Unity.Analyzers.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Correctness.
        /// </summary>
        internal static string CategoryCorrectness {
            get {
                return ResourceManager.GetString("CategoryCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Performance.
        /// </summary>
        internal static string CategoryPerformance {
            get {
                return ResourceManager.GetString("CategoryPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Safety.
        /// </summary>
        internal static string CategoryTypeSafety {
            get {
                return ResourceManager.GetString("CategoryTypeSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Component &apos;{0}&apos; should not be instantiated directly..
        /// </summary>
        internal static string CreateComponentInstanceDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("CreateComponentInstanceDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Component instance creation.
        /// </summary>
        internal static string CreateComponentInstanceDiagnosticTitle {
            get {
                return ResourceManager.GetString("CreateComponentInstanceDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use gameObject.AddComponent().
        /// </summary>
        internal static string CreateMonoBehaviourInstanceCodeFixTitle {
            get {
                return ResourceManager.GetString("CreateMonoBehaviourInstanceCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use AddComponent() to create MonoBehaviours. A MonoBehaviour component needs to be attached to a GameObject..
        /// </summary>
        internal static string CreateMonoBehaviourInstanceDiagnosticDescription {
            get {
                return ResourceManager.GetString("CreateMonoBehaviourInstanceDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use ScriptableObject.CreateInstance().
        /// </summary>
        internal static string CreateScriptableObjectInstanceCodeFixTitle {
            get {
                return ResourceManager.GetString("CreateScriptableObjectInstanceCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use CreateInstance() to create a ScriptableObject. To handle Unity message methods, the Unity engine needs to create the ScriptableObject..
        /// </summary>
        internal static string CreateScriptableObjectInstanceDiagnosticDescription {
            get {
                return ResourceManager.GetString("CreateScriptableObjectInstanceDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ScriptableObject &apos;{0}&apos; should not be instantiated directly..
        /// </summary>
        internal static string CreateScriptableObjectInstanceDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("CreateScriptableObjectInstanceDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ScriptableObject instance creation.
        /// </summary>
        internal static string CreateScriptableObjectInstanceDiagnosticTitle {
            get {
                return ResourceManager.GetString("CreateScriptableObjectInstanceDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use gameObject instead.
        /// </summary>
        internal static string DestroyTransformCodeFixTitle {
            get {
                return ResourceManager.GetString("DestroyTransformCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot destroy a Transform component of a GameObject, but you can destroy the whole GameObject..
        /// </summary>
        internal static string DestroyTransformDiagnosticDescription {
            get {
                return ResourceManager.GetString("DestroyTransformDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calling Destroy or DestroyImmediate on a Transform is not allowed..
        /// </summary>
        internal static string DestroyTransformDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("DestroyTransformDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calling Destroy or DestroyImmediate on a Transform.
        /// </summary>
        internal static string DestroyTransformDiagnosticTitle {
            get {
                return ResourceManager.GetString("DestroyTransformDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove empty Unity message.
        /// </summary>
        internal static string EmptyUnityMessageCodeFixTitle {
            get {
                return ResourceManager.GetString("EmptyUnityMessageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity messages are called by the runtime even if they&apos;re empty. Remove them to avoid unnecessary processing..
        /// </summary>
        internal static string EmptyUnityMessageDiagnosticDescription {
            get {
                return ResourceManager.GetString("EmptyUnityMessageDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Unity message &apos;{0}&apos; is empty..
        /// </summary>
        internal static string EmptyUnityMessageDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("EmptyUnityMessageDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty Unity message.
        /// </summary>
        internal static string EmptyUnityMessageDiagnosticTitle {
            get {
                return ResourceManager.GetString("EmptyUnityMessageDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Time.fixedDeltaTime.
        /// </summary>
        internal static string FixedUpdateWithoutDeltaTimeCodeFixTitle {
            get {
                return ResourceManager.GetString("FixedUpdateWithoutDeltaTimeCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FixedUpdate is independent of the frame rate. Use Time.fixedDeltaTime instead of Time.deltaTime..
        /// </summary>
        internal static string FixedUpdateWithoutDeltaTimeDiagnosticDescription {
            get {
                return ResourceManager.GetString("FixedUpdateWithoutDeltaTimeDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FixedUpdate should use Time.fixedDeltaTime..
        /// </summary>
        internal static string FixedUpdateWithoutDeltaTimeDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("FixedUpdateWithoutDeltaTimeDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time.deltaTime used with FixedUpdate.
        /// </summary>
        internal static string FixedUpdateWithoutDeltaTimeDiagnosticTitle {
            get {
                return ResourceManager.GetString("FixedUpdateWithoutDeltaTimeDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GetComponent only supports arguments that are a Unity Component or an interface type..
        /// </summary>
        internal static string GetComponentIncorrectTypeDiagnosticDescription {
            get {
                return ResourceManager.GetString("GetComponentIncorrectTypeDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; is not a Unity Component..
        /// </summary>
        internal static string GetComponentIncorrectTypeDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("GetComponentIncorrectTypeDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid type for call to GetComponent.
        /// </summary>
        internal static string GetComponentIncorrectTypeDiagnosticTitle {
            get {
                return ResourceManager.GetString("GetComponentIncorrectTypeDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t flag private methods decorated with PreserveAttribute or UsedImplicitlyAttribute as unused..
        /// </summary>
        internal static string ImplicitUsageAttributeSuppressorJustification {
            get {
                return ResourceManager.GetString("ImplicitUsageAttributeSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use static method.
        /// </summary>
        internal static string ImproperMenuItemMethodCodeFixTitle {
            get {
                return ResourceManager.GetString("ImproperMenuItemMethodCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MenuItem can only be used on static methods..
        /// </summary>
        internal static string ImproperMenuItemMethodDiagnosticDescription {
            get {
                return ResourceManager.GetString("ImproperMenuItemMethodDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is not a static method..
        /// </summary>
        internal static string ImproperMenuItemMethodDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("ImproperMenuItemMethodDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Make method static.
        /// </summary>
        internal static string ImproperMenuItemMethodDiagnosticTitle {
            get {
                return ResourceManager.GetString("ImproperMenuItemMethodDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove SerializeField attribute.
        /// </summary>
        internal static string ImproperSerializeFieldCodeFixTitle {
            get {
                return ResourceManager.GetString("ImproperSerializeFieldCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SerializeField attribute does not work on properties, and are unnecessary for public fields..
        /// </summary>
        internal static string ImproperSerializeFieldDiagnosticDescription {
            get {
                return ResourceManager.GetString("ImproperSerializeFieldDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SerializeField attribute is invalid or redundant for property or field: &apos;{0}&apos;..
        /// </summary>
        internal static string ImproperSerializeFieldDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("ImproperSerializeFieldDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove invalid SerializeField attribute.
        /// </summary>
        internal static string ImproperSerializeFieldDiagnosticTitle {
            get {
                return ResourceManager.GetString("ImproperSerializeFieldDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove indirection call.
        /// </summary>
        internal static string IndirectionMessageCodeFixTitle {
            get {
                return ResourceManager.GetString("IndirectionMessageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not use unnecessary indirection..
        /// </summary>
        internal static string IndirectionMessageDiagnosticDescription {
            get {
                return ResourceManager.GetString("IndirectionMessageDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indirection is redundant.
        /// </summary>
        internal static string IndirectionMessageDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("IndirectionMessageDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indirection call.
        /// </summary>
        internal static string IndirectionMessageDiagnosticTitle {
            get {
                return ResourceManager.GetString("IndirectionMessageDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add static constructor.
        /// </summary>
        internal static string InitializeOnLoadStaticCtorCodeFixTitle {
            get {
                return ResourceManager.GetString("InitializeOnLoadStaticCtorCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provide a static constructor when applying the InitializeOnLoad attribute to a class. This will call it when the editor launches..
        /// </summary>
        internal static string InitializeOnLoadStaticCtorDiagnosticDescription {
            get {
                return ResourceManager.GetString("InitializeOnLoadStaticCtorDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class &apos;{0}&apos; decorated with the InitializeOnLoad attribute is missing a static constructor..
        /// </summary>
        internal static string InitializeOnLoadStaticCtorDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("InitializeOnLoadStaticCtorDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing static constructor with InitializeOnLoad.
        /// </summary>
        internal static string InitializeOnLoadStaticCtorDiagnosticTitle {
            get {
                return ResourceManager.GetString("InitializeOnLoadStaticCtorDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use KeyCode argument.
        /// </summary>
        internal static string InputGetKeyCodeFixTitle {
            get {
                return ResourceManager.GetString("InputGetKeyCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usage of the method overload with KeyCode argument is preferred..
        /// </summary>
        internal static string InputGetKeyDiagnosticDescription {
            get {
                return ResourceManager.GetString("InputGetKeyDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A method overload with KeyCode argument exists..
        /// </summary>
        internal static string InputGetKeyDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("InputGetKeyDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input.GetKey overloads with KeyCode argument.
        /// </summary>
        internal static string InputGetKeyDiagnosticTitle {
            get {
                return ResourceManager.GetString("InputGetKeyDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fix method signature.
        /// </summary>
        internal static string LoadAttributeMethodCodeFixTitle {
            get {
                return ResourceManager.GetString("LoadAttributeMethodCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity needs a method decorated with InitializeOnLoadMethod, RuntimeInitializeOnLoadMethod or DidReloadScripts attribute to be static and parameterless. Else either Unity won&apos;t call it or will throw NullReferenceException..
        /// </summary>
        internal static string LoadAttributeMethodDiagnosticDescription {
            get {
                return ResourceManager.GetString("LoadAttributeMethodDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method &apos;{0}&apos; decorated with InitializeOnLoadMethod, RuntimeInitializeOnLoadMethod or DidReloadScripts attribute must be static and parameterless..
        /// </summary>
        internal static string LoadAttributeMethodDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("LoadAttributeMethodDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use a static and parameterless method.
        /// </summary>
        internal static string LoadAttributeMethodDiagnosticTitle {
            get {
                return ResourceManager.GetString("LoadAttributeMethodDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t flag private methods decorated with InitializeOnLoadMethod, RuntimeInitializeOnLoadMethod or DidReloadScripts attribute as unused..
        /// </summary>
        internal static string LoadAttributeMethodSuppressorJustification {
            get {
                return ResourceManager.GetString("LoadAttributeMethodSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fix message signature.
        /// </summary>
        internal static string MessageSignatureCodeFixTitle {
            get {
                return ResourceManager.GetString("MessageSignatureCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Unity message uses an incorrect method signature..
        /// </summary>
        internal static string MessageSignatureDiagnosticDescription {
            get {
                return ResourceManager.GetString("MessageSignatureDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Unity message &apos;{0}&apos; has an incorrect signature..
        /// </summary>
        internal static string MessageSignatureDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("MessageSignatureDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect message signature.
        /// </summary>
        internal static string MessageSignatureDiagnosticTitle {
            get {
                return ResourceManager.GetString("MessageSignatureDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Unity runtime invokes Unity messages..
        /// </summary>
        internal static string MessageSuppressorJustification {
            get {
                return ResourceManager.GetString("MessageSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usage of nameof or direct call is preferred for type safety..
        /// </summary>
        internal static string MethodInvocationDiagnosticDescription {
            get {
                return ResourceManager.GetString("MethodInvocationDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method &apos;{0}&apos; is invoked using a string literal..
        /// </summary>
        internal static string MethodInvocationDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("MethodInvocationDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsafe way to get the method name.
        /// </summary>
        internal static string MethodInvocationDiagnosticTitle {
            get {
                return ResourceManager.GetString("MethodInvocationDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use direct call.
        /// </summary>
        internal static string MethodInvocationDirectCallCodeFixTitle {
            get {
                return ResourceManager.GetString("MethodInvocationDirectCallCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use nameof operator.
        /// </summary>
        internal static string MethodInvocationNameOfCodeFixTitle {
            get {
                return ResourceManager.GetString("MethodInvocationNameOfCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t flag fields with a SerializeField or SerializeReference attribute as never assigned..
        /// </summary>
        internal static string NeverAssignedSerializeFieldSuppressorJustification {
            get {
                return ResourceManager.GetString("NeverAssignedSerializeFieldSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use the generic form of GetComponent.
        /// </summary>
        internal static string NonGenericGetComponentCodeFixTitle {
            get {
                return ResourceManager.GetString("NonGenericGetComponentCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usage of the generic form of GetComponent is preferred for type safety..
        /// </summary>
        internal static string NonGenericGetComponentDiagnosticDescription {
            get {
                return ResourceManager.GetString("NonGenericGetComponentDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method &apos;{0}&apos; has a preferred generic overload..
        /// </summary>
        internal static string NonGenericGetComponentDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("NonGenericGetComponentDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usage of non generic GetComponent.
        /// </summary>
        internal static string NonGenericGetComponentDiagnosticTitle {
            get {
                return ResourceManager.GetString("NonGenericGetComponentDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objects deriving from &apos;UnityEngine.Object&apos; cannot be initialized..
        /// </summary>
        internal static string NullableReferenceTypesSuppressorJustification {
            get {
                return ResourceManager.GetString("NullableReferenceTypesSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avoid using allocating versions of Physics functions..
        /// </summary>
        internal static string PhysicsAllocMethodUsageDiagnosticDescription {
            get {
                return ResourceManager.GetString("PhysicsAllocMethodUsageDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compared to &apos;{0}&apos;, &apos;{1}&apos; is not allocating memory..
        /// </summary>
        internal static string PhysicsAllocMethodUsageDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("PhysicsAllocMethodUsageDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use non-allocating physics APIs.
        /// </summary>
        internal static string PhysicsAllocMethodUsageDiagnosticTitle {
            get {
                return ResourceManager.GetString("PhysicsAllocMethodUsageDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove PropertyDrawer.OnGUI() call.
        /// </summary>
        internal static string PropertyDrawerOnGUICodeFixTitle {
            get {
                return ResourceManager.GetString("PropertyDrawerOnGUICodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default implementation for PropertyDrawer.OnGUI() will display &quot;no GUI implemented&quot; in the inspector..
        /// </summary>
        internal static string PropertyDrawerOnGUIDiagnosticDescription {
            get {
                return ResourceManager.GetString("PropertyDrawerOnGUIDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PropertyDrawer.OnGUI() will display &quot;no GUI implemented&quot; in the inspector..
        /// </summary>
        internal static string PropertyDrawerOnGUIDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("PropertyDrawerOnGUIDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not call PropertyDrawer.OnGUI().
        /// </summary>
        internal static string PropertyDrawerOnGUIDiagnosticTitle {
            get {
                return ResourceManager.GetString("PropertyDrawerOnGUIDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Make Unity message protected.
        /// </summary>
        internal static string ProtectedUnityMessageCodeFixTitle {
            get {
                return ResourceManager.GetString("ProtectedUnityMessageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity message should be protected..
        /// </summary>
        internal static string ProtectedUnityMessageDiagnosticDescription {
            get {
                return ResourceManager.GetString("ProtectedUnityMessageDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity message should be protected..
        /// </summary>
        internal static string ProtectedUnityMessageDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("ProtectedUnityMessageDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefer protected Unity Message..
        /// </summary>
        internal static string ProtectedUnityMessageDiagnosticTitle {
            get {
                return ResourceManager.GetString("ProtectedUnityMessageDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t set fields with a ContextMenuItem attribute as readonly..
        /// </summary>
        internal static string ReadonlyContextMenuItemJustification {
            get {
                return ResourceManager.GetString("ReadonlyContextMenuItemJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t set fields with a SerializeField or SerializeReference attributes to read-only..
        /// </summary>
        internal static string ReadonlySerializeFieldSuppressorJustification {
            get {
                return ResourceManager.GetString("ReadonlySerializeFieldSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You should not use System.Reflection features in performance critical messages..
        /// </summary>
        internal static string ReflectionDiagnosticDescription {
            get {
                return ResourceManager.GetString("ReflectionDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System.Reflection usage detected in performance critical message &apos;{0}&apos;..
        /// </summary>
        internal static string ReflectionDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("ReflectionDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System.Reflection features in performance critical messages.
        /// </summary>
        internal static string ReflectionDiagnosticTitle {
            get {
                return ResourceManager.GetString("ReflectionDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compared to SetPixels, SetPixels32 is much faster and uses less memory..
        /// </summary>
        internal static string SetPixelsMethodUsageDiagnosticDescription {
            get {
                return ResourceManager.GetString("SetPixelsMethodUsageDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; is slower than SetPixels32..
        /// </summary>
        internal static string SetPixelsMethodUsageDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("SetPixelsMethodUsageDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SetPixels invocation is slow.
        /// </summary>
        internal static string SetPixelsMethodUsageDiagnosticTitle {
            get {
                return ResourceManager.GetString("SetPixelsMethodUsageDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use SetPositionAndRotation() method.
        /// </summary>
        internal static string SetPositionAndRotationCodeFixTitle {
            get {
                return ResourceManager.GetString("SetPositionAndRotationCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefer using SetPositionAndRotation() method..
        /// </summary>
        internal static string SetPositionAndRotationDiagnosticDescription {
            get {
                return ResourceManager.GetString("SetPositionAndRotationDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assigning position and rotation sequentially could be optimized..
        /// </summary>
        internal static string SetPositionAndRotationDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("SetPositionAndRotationDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inefficient position/rotation assignment.
        /// </summary>
        internal static string SetPositionAndRotationDiagnosticTitle {
            get {
                return ResourceManager.GetString("SetPositionAndRotationDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use CompareTag method.
        /// </summary>
        internal static string TagComparisonCodeFixTitle {
            get {
                return ResourceManager.GetString("TagComparisonCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparing tags using == is slower than using the built-in CompareTag method..
        /// </summary>
        internal static string TagComparisonDiagnosticDescription {
            get {
                return ResourceManager.GetString("TagComparisonDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparing tags using == is inefficient..
        /// </summary>
        internal static string TagComparisonDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("TagComparisonDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inefficient tag comparison.
        /// </summary>
        internal static string TagComparisonDiagnosticTitle {
            get {
                return ResourceManager.GetString("TagComparisonDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not use Throw expressions with Unity objects..
        /// </summary>
        internal static string ThrowExpressionSuppressorJustification {
            get {
                return ResourceManager.GetString("ThrowExpressionSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use TryGetComponent instead.
        /// </summary>
        internal static string TryGetComponentCodeFixTitle {
            get {
                return ResourceManager.GetString("TryGetComponentCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TryGetComponent will not allocate memory in case it fails..
        /// </summary>
        internal static string TryGetComponentDiagnosticDescription {
            get {
                return ResourceManager.GetString("TryGetComponentDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GetComponent allocates even if no component is found..
        /// </summary>
        internal static string TryGetComponentDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("TryGetComponentDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GetComponent always allocates.
        /// </summary>
        internal static string TryGetComponentDiagnosticTitle {
            get {
                return ResourceManager.GetString("TryGetComponentDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use null comparison.
        /// </summary>
        internal static string UnityObjectCoalescingAssignmentCodeFixTitle {
            get {
                return ResourceManager.GetString("UnityObjectCoalescingAssignmentCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity overrides the null comparison operator for Unity objects, which is incompatible with coalescing assignment..
        /// </summary>
        internal static string UnityObjectCoalescingAssignmentDiagnosticDescription {
            get {
                return ResourceManager.GetString("UnityObjectCoalescingAssignmentDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity objects should not use coalescing assignment..
        /// </summary>
        internal static string UnityObjectCoalescingAssignmentDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("UnityObjectCoalescingAssignmentDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coalescing assignment on Unity objects.
        /// </summary>
        internal static string UnityObjectCoalescingAssignmentDiagnosticTitle {
            get {
                return ResourceManager.GetString("UnityObjectCoalescingAssignmentDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity objects should not use coalescing assignment..
        /// </summary>
        internal static string UnityObjectCoalescingAssignmentSuppressorJustification {
            get {
                return ResourceManager.GetString("UnityObjectCoalescingAssignmentSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use null comparison.
        /// </summary>
        internal static string UnityObjectImplicitBoolCodeFixTitle {
            get {
                return ResourceManager.GetString("UnityObjectImplicitBoolCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use null comparison instead of implicit bool operator..
        /// </summary>
        internal static string UnityObjectImplicitBoolDiagnosticDescription {
            get {
                return ResourceManager.GetString("UnityObjectImplicitBoolDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use null comparison instead of implicit bool operator..
        /// </summary>
        internal static string UnityObjectImplicitBoolDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("UnityObjectImplicitBoolDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use null comparison instead of implicit bool operator..
        /// </summary>
        internal static string UnityObjectImplicitBoolDiagnosticTitle {
            get {
                return ResourceManager.GetString("UnityObjectImplicitBoolDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use null comparison.
        /// </summary>
        internal static string UnityObjectIsPatternCodeFixTitle {
            get {
                return ResourceManager.GetString("UnityObjectIsPatternCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity overrides the null comparison operator for Unity objects, which is incompatible with pattern matching with null..
        /// </summary>
        internal static string UnityObjectIsPatternDiagnosticDescription {
            get {
                return ResourceManager.GetString("UnityObjectIsPatternDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity objects should not use pattern matching with null..
        /// </summary>
        internal static string UnityObjectIsPatternDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("UnityObjectIsPatternDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pattern matching with null on Unity objects.
        /// </summary>
        internal static string UnityObjectIsPatternDiagnosticTitle {
            get {
                return ResourceManager.GetString("UnityObjectIsPatternDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use null comparison.
        /// </summary>
        internal static string UnityObjectNullCoalescingCodeFixTitle {
            get {
                return ResourceManager.GetString("UnityObjectNullCoalescingCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity overrides the null comparison operator for Unity objects, which is incompatible with null coalescing..
        /// </summary>
        internal static string UnityObjectNullCoalescingDiagnosticDescription {
            get {
                return ResourceManager.GetString("UnityObjectNullCoalescingDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity objects should not use null coalescing..
        /// </summary>
        internal static string UnityObjectNullCoalescingDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("UnityObjectNullCoalescingDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Null coalescing on Unity objects.
        /// </summary>
        internal static string UnityObjectNullCoalescingDiagnosticTitle {
            get {
                return ResourceManager.GetString("UnityObjectNullCoalescingDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity objects should not use null coalescing..
        /// </summary>
        internal static string UnityObjectNullCoalescingSuppressorJustification {
            get {
                return ResourceManager.GetString("UnityObjectNullCoalescingSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use null comparison.
        /// </summary>
        internal static string UnityObjectNullPropagationCodeFixTitle {
            get {
                return ResourceManager.GetString("UnityObjectNullPropagationCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity overrides the null comparison operator for Unity objects, which is incompatible with null propagation..
        /// </summary>
        internal static string UnityObjectNullPropagationDiagnosticDescription {
            get {
                return ResourceManager.GetString("UnityObjectNullPropagationDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity objects should not use null propagation..
        /// </summary>
        internal static string UnityObjectNullPropagationDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("UnityObjectNullPropagationDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Null propagation on Unity objects.
        /// </summary>
        internal static string UnityObjectNullPropagationDiagnosticTitle {
            get {
                return ResourceManager.GetString("UnityObjectNullPropagationDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity objects should not use null propagation..
        /// </summary>
        internal static string UnityObjectNullPropagationSuppressorJustification {
            get {
                return ResourceManager.GetString("UnityObjectNullPropagationSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t flag fields with a ContextMenuItem attribute as unused..
        /// </summary>
        internal static string UnusedContextMenuItemJustification {
            get {
                return ResourceManager.GetString("UnusedContextMenuItemJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use StartCoroutine().
        /// </summary>
        internal static string UnusedCoroutineReturnValueCodeFixTitle {
            get {
                return ResourceManager.GetString("UnusedCoroutineReturnValueCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use StartCoroutine() to start a coroutine. Calling the coroutine method directly will result in the coroutine never being executed..
        /// </summary>
        internal static string UnusedCoroutineReturnValueDiagnosticDescription {
            get {
                return ResourceManager.GetString("UnusedCoroutineReturnValueDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coroutine &apos;{0}&apos; should be called using StartCoroutine()..
        /// </summary>
        internal static string UnusedCoroutineReturnValueDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("UnusedCoroutineReturnValueDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unused Unity Coroutine.
        /// </summary>
        internal static string UnusedCoroutineReturnValueDiagnosticTitle {
            get {
                return ResourceManager.GetString("UnusedCoroutineReturnValueDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t flag methods with MenuItem/ContextMenu attribute or referenced by a field with the ContextMenuItem attribute as unused..
        /// </summary>
        internal static string UnusedMethodContextMenuSuppressorJustification {
            get {
                return ResourceManager.GetString("UnusedMethodContextMenuSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t flag private methods used with Invoke/InvokeRepeating or StartCoroutine/StopCoroutine as unused..
        /// </summary>
        internal static string UnusedMethodSuppressorJustification {
            get {
                return ResourceManager.GetString("UnusedMethodSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t flag private fields with a SerializeField or SerializeReference attribute as unused..
        /// </summary>
        internal static string UnusedSerializeFieldSuppressorJustification {
            get {
                return ResourceManager.GetString("UnusedSerializeFieldSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Time.deltaTime.
        /// </summary>
        internal static string UpdateWithoutFixedDeltaTimeCodeFixTitle {
            get {
                return ResourceManager.GetString("UpdateWithoutFixedDeltaTimeCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update is dependent on the frame rate. Use Time.deltaTime instead of Time.fixedDeltaTime..
        /// </summary>
        internal static string UpdateWithoutFixedDeltaTimeDiagnosticDescription {
            get {
                return ResourceManager.GetString("UpdateWithoutFixedDeltaTimeDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update should use Time.deltaTime..
        /// </summary>
        internal static string UpdateWithoutFixedDeltaTimeDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("UpdateWithoutFixedDeltaTimeDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time.fixedDeltaTime used with Update.
        /// </summary>
        internal static string UpdateWithoutFixedDeltaTimeDiagnosticTitle {
            get {
                return ResourceManager.GetString("UpdateWithoutFixedDeltaTimeDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Re-order operands.
        /// </summary>
        internal static string VectorMathCodeFixTitle {
            get {
                return ResourceManager.GetString("VectorMathCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scalar calculations are faster than vector calculations..
        /// </summary>
        internal static string VectorMathDiagnosticDescription {
            get {
                return ResourceManager.GetString("VectorMathDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Re-order operands for better performance..
        /// </summary>
        internal static string VectorMathDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("VectorMathDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give priority to scalar calculations over vector calculations.
        /// </summary>
        internal static string VectorMathDiagnosticTitle {
            get {
                return ResourceManager.GetString("VectorMathDiagnosticTitle", resourceCulture);
            }
        }
    }
}
